# This is my alacritty config
# author: Bruno de Lima <github.com/brunodles>

[general]
import = [
	"~/.config/alacritty/env.toml",
	"~/.config/alacritty/colors.toml",
	"~/.config/alacritty/keyboard.toml",
#	"~/.config/alacritty/window_linux.toml",
#	"~/.config/alacritty/window_mac.toml",
]
live_config_reload = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
