services:
  plex:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    environment:
      PGID: "1000"
      PUID: "1000"
      VERSION: docker
    hostname: plex
    image: lscr.io/linuxserver/plex:1.40.5
    restart: unless-stopped
    volumes:
      - $HOME/data/plex/config:/config
      - /DATA/Media:/Media
      - /media/data:/DataHd
