#!/bin/bash
# Install interpreter
# This script will forward the configuration into the './generator.sh'  that will evaluate which commands should be
# performed.
# This script acts as a performer of the commands generated by the python script, as dealing with subprocess and scripts
# on python might break the interaction with CLI tools.
# Author: Bruno de Lima <github.com/brunodles>

tmp_script=/tmp/install_script.sh
install_dir=$(dirname $0)
if [ -f "$tmp_script" ]; then
  rm $tmp_script
fi

$install_dir/generator.sh $@ >> $tmp_script

export PS4='\n--------------------------------------\n + '
bash -x $tmp_script
rm $tmp_script