#!/usr/bin/env bash
# Link files
source=$1
target=$2
if [ -f "$target" ]; then
  # if parameter contains '--no-bak'
  rm $target
  # else
  mv "$target" "$target.bak"
  # done
fi
mkdir -p $(dirname "$target")
ln -s $source $target
