services:
  syncthing:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    hostname: syncthing
    image: linuxserver/syncthing:1.29.2
      #    ports:
      #      - "8384:8384"
      #      - "22000:22000"
      #      - "21027:21027"
    restart: unless-stopped
    volumes:
      - $HOME/data/syncthing/config:/config
      - /mnt/backup_media/backups:/DATA

    networks:
      - proxy
    labels:
      # Explicitly tells Traefik to expose this container
      - traefik.enable=true 
      # Routes traffic targeting this domain
      - traefik.http.routers.syncthing.rule=Host(`syncthing.media.lab`) 
      # Binds this route to the HTTP port
      - traefik.http.routers.syncthing.entrypoints=web 
      # Container internal port
      - traefik.http.services.syncthing.loadbalancer.server.port=8384 

networks:
  proxy:
    name: proxy
    external: true
    

