services:
  syncthing:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
    hostname: syncthing
    image: linuxserver/syncthing:1.29.2
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    restart: unless-stopped
    volumes:
      - $HOME/data/syncthing/config:/config
      - /media/data:/DATA
