#!/bin/bash

SESH="test"

tmux has-session -t $SESH 2>/dev/null

if [ $? != 0 ]; then
  tmux new-session -d -s $SESH -n "editor"

  tmux send-keys -t "$SESH:editor" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:editor" "vim ." C-m

  tmux new-window -t "$SESH" -n "files"
  tmux send-keys -t "$SESH:files" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:file" "ls" C-m

  tmux new-window -t "$SESH" -n "split_h"
  tmux send-keys -t "$SESH:split_h" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:split_h" "ls -alsh" C-m
  tmux split-window -h
  tmux send-keys -t "$SESH:split_h" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:split_h" "ls -l" C-m

  tmux new-window -t "$SESH" -n "split_v"
  tmux send-keys -t "$SESH:split_v" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:split_v" "ls -alsh" C-m
  tmux split-window -v
  tmux send-keys -t "$SESH:split_v" "cd ~/workspace" C-m
  tmux send-keys -t "$SESH:split_v" "ls -l" C-m


  tmux select-window -t "$SESH:editor"
fi

tmux attach-session -t $SESH

