#!/data/data/com.termux/files/usr/bin/bash
# configure.sh — Configure Android/Termux settings
#
# Run after install.sh:
#   cd ~/dotfiles && bash hosts/android/bootstrap/configure.sh

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
source "$HOME/dotfiles/scripts/bootstrap/_env.source.sh"

if [[ ! -d /data/data/com.termux ]]; then
  error "This script must run inside Termux on Android."
  exit 1
fi

link="$SCRIPT_BOOTSTRAP_DIR/link"

# ──────────────────────────────────────────────
# 5. Copy Termux extra-keys config
# ──────────────────────────────────────────────
info "Configuring Termux extra-keys..."
mkdir -p "$HOME/.termux"
if [[ -f "$HOST_DIR/termux/termux.properties" ]]; then
  bash "$link" "$HOST_DIR/termux/termux.properties" "$HOME/.termux/termux.properties"
  termux-reload-settings 2>/dev/null || true
fi

# ──────────────────────────────────────────────
# 7. Copy custom scripts to ~/.local/bin
# ──────────────────────────────────────────────
info "Copying Termux scripts..."
mkdir -p "$HOME/.local/bin"

if [[ -d "$HOST_DIR/home/.local/bin" ]]; then
  cp -r "$HOST_DIR/home/.local/bin/"* "$HOME/.local/bin/"
  chmod +x "$HOME/.local/bin/"*
  info "  Scripts installed:"
  ls -1 "$HOME/.local/bin/"
fi

# ──────────────────────────────────────────────
# 8. set default shell
# ──────────────────────────────────────────────
chsh -s zsh

# ──────────────────────────────────────────────
# 9. SSH authorized keys
# ──────────────────────────────────────────────
info "Setting up SSH authorized_keys..."
AUTH_KEYS="$HOME/.ssh/authorized_keys"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

SSHD_CONFIG="$PREFIX/etc/ssh/sshd_config.d/port.conf"
if [[ ! -f "$SSHD_CONFIG" ]] || ! grep -q "Port 8022" "$SSHD_CONFIG" 2>/dev/null; then
  mkdir -p "$(dirname "$SSHD_CONFIG")"
  echo "Port 8022" > "$SSHD_CONFIG"
  info "  SSH configured on port 8022"
fi

if [[ -f "$HOST_DIR/ssh/authorized_keys" ]]; then
  cp "$HOST_DIR/ssh/authorized_keys" "$AUTH_KEYS"
  info "  Copied authorized_keys from repo."
elif [[ ! -f "$AUTH_KEYS" ]]; then
  warn "  No authorized_keys found. Add your public key manually:"
  warn "    echo 'ssh-ed25519 AAAA...' >> ~/.ssh/authorized_keys"
else
  info "  authorized_keys already exists."
fi
chmod 600 "$AUTH_KEYS" 2>/dev/null || true

# ──────────────────────────────────────────────
# 11. Create ~/workspace directory
# ──────────────────────────────────────────────
mkdir -p "$HOME/workspace"
info "Workspace directory ready at ~/workspace"

# ──────────────────────────────────────────────
# 12. DNS — Dnsmasq
# ──────────────────────────────────────────────
info "Deploying Dnsmasq config..."

if [[ -f "$PREFIX/etc/dnsmasq.conf" ]]; then
  info "  Config already exists at $PREFIX/etc/dnsmasq.conf"
  if ! grep -q "Generated by apply-dns.sh\|dnsmasq.conf for Android server" "$PREFIX/etc/dnsmasq.conf" 2>/dev/null; then
    warn "  Existing config appears to be from a different source."
    warn "  Backup saved to $PREFIX/etc/dnsmasq.conf.bak"
    cp "$PREFIX/etc/dnsmasq.conf" "$PREFIX/etc/dnsmasq.conf.bak.$(date +%Y%m%d)"
    cp "$HOST_DIR/dns/dnsmasq.conf" "$PREFIX/etc/dnsmasq.conf"
    sv restart dnsmasq 2>/dev/null || true
    ok "Config replaced with managed version"
  fi
else
  info "  Deploying reference config..."
  cp "$HOST_DIR/dns/dnsmasq.conf" "$PREFIX/etc/dnsmasq.conf"
  ok "Config deployed from reference"
  info "  It contains example IPs — regenerate for your network:"
  info "  bash scripts/dns/apply-dns.sh --host android"
  sv restart dnsmasq 2>/dev/null || true
fi

info "  Update config: cd ~/dotfiles && bash scripts/dns/apply-dns.sh --host android"
info "  Test: dig @localhost google.com"

# ── Done ──
echo ""
info "═══════════════════════════════════════════"
info "  ✅ Android configure complete!"
info "  ➜  Run links.sh to symlink dotfiles"
info "═══════════════════════════════════════════"
echo ""
