services:
  gitea:
    image: gitea/gitea:1.22.4
    hostname: gitea
    restart: unless-stopped
    environment:
      USER: "git"
      RUN_USER: "git"
      USER_GID: "1000"
      USER_UID: "1000"
      #    ports:
      #      - 3000:3000
      #      - 222:22
      # Ports are linked through traefik
    volumes:
      - /home/bruno/data/gitea/data:/data
    networks:
      - proxy
    labels:
      # Explicitly tells Traefik to expose this container
      - traefik.enable=true 
      # Routes traffic targeting this domain
      - traefik.http.routers.gitea.rule=Host(`gitea.media.lab`) 
      # Binds this route to the HTTP port
      - traefik.http.routers.gitea.entrypoints=web 
      # Container internal port
      - traefik.http.services.gitea.loadbalancer.server.port=3000 

networks:
  proxy:
    name: proxy
    external: true
    
