#!/bin/bash
# List the files that should be used to sync with home
# Author: brunodles <github.com/brunodles>
# Parameters:
# 1 the path to sync with home

CONFIG_FILE_NAME=".linker"

ignoredFiles=""
initialDir="$(pwd)/$1/"
configFilePath="$initialDir/$CONFIG_FILE_NAME"
fullFilesCommand="find $initialDir -type f"
files=""

# Read configu files if they exist
if [ -f "$configFilePath" ]; then
  ignoredFiles=$(cat $configFilePath)
fi

# Compose the full files command
fullFilesCommand+=" -not -path \"*/$CONFIG_FILE_NAME\""
while read p; do
  if [[ "$p" == "i "* ]]; then
    fullFilesCommand+=" -not -path \"*${p#i }\""
  fi
done <$configFilePath

# Find the files by evaluating the find command
#echo "Command: $fullFilesCommand"
files=$(eval $fullFilesCommand)

for i in $files ; do
  echo "* ${i#$initialDir}"
done

